/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 404 response
 */
export type GetApiV1TriggerTriggerIdNotFoundErrorData = {
  error: operations.ErrorTriggerNotFound;
};

/**
 * HTTP 404 response
 */
export class GetApiV1TriggerTriggerIdNotFoundError extends LinkageError {
  error: operations.ErrorTriggerNotFound;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1TriggerTriggerIdNotFoundErrorData;

  constructor(
    err: GetApiV1TriggerTriggerIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1TriggerTriggerIdNotFoundError";
  }
}

/**
 * HTTP 400 response
 */
export type GetApiV1TriggerTriggerIdBadRequestErrorData = {
  error: operations.ErrorTriggerIDIsRequired;
};

/**
 * HTTP 400 response
 */
export class GetApiV1TriggerTriggerIdBadRequestError extends LinkageError {
  error: operations.ErrorTriggerIDIsRequired;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1TriggerTriggerIdBadRequestErrorData;

  constructor(
    err: GetApiV1TriggerTriggerIdBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1TriggerTriggerIdBadRequestError";
  }
}

/** @internal */
export const GetApiV1TriggerTriggerIdNotFoundError$inboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorTriggerNotFound$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1TriggerTriggerIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetApiV1TriggerTriggerIdNotFoundError$Outbound = {
  error: operations.ErrorTriggerNotFound$Outbound;
};

/** @internal */
export const GetApiV1TriggerTriggerIdNotFoundError$outboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdNotFoundError$Outbound,
  z.ZodTypeDef,
  GetApiV1TriggerTriggerIdNotFoundError
> = z.instanceof(GetApiV1TriggerTriggerIdNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.ErrorTriggerNotFound$outboundSchema),
  }));

/** @internal */
export const GetApiV1TriggerTriggerIdBadRequestError$inboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorTriggerIDIsRequired$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1TriggerTriggerIdBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetApiV1TriggerTriggerIdBadRequestError$Outbound = {
  error: operations.ErrorTriggerIDIsRequired$Outbound;
};

/** @internal */
export const GetApiV1TriggerTriggerIdBadRequestError$outboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdBadRequestError$Outbound,
  z.ZodTypeDef,
  GetApiV1TriggerTriggerIdBadRequestError
> = z.instanceof(GetApiV1TriggerTriggerIdBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.ErrorTriggerIDIsRequired$outboundSchema),
  }));
