/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 500 response
 */
export type GetApiV1FeaturesInternalServerErrorData = {
  error: operations.GetApiV1FeaturesErrorProjectHasAnInvalidConfiguration;
};

/**
 * HTTP 500 response
 */
export class GetApiV1FeaturesInternalServerError extends LinkageError {
  error: operations.GetApiV1FeaturesErrorProjectHasAnInvalidConfiguration;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1FeaturesInternalServerErrorData;

  constructor(
    err: GetApiV1FeaturesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1FeaturesInternalServerError";
  }
}

/**
 * HTTP 401 response
 */
export type GetApiV1FeaturesUnauthorizedErrorData = {
  error: operations.GetApiV1FeaturesUnauthorizedError;
};

/**
 * HTTP 401 response
 */
export class GetApiV1FeaturesUnauthorizedError extends LinkageError {
  error: operations.GetApiV1FeaturesUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1FeaturesUnauthorizedErrorData;

  constructor(
    err: GetApiV1FeaturesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1FeaturesUnauthorizedError";
  }
}

/**
 * HTTP 404 response
 */
export type GetApiV1NodeTypesNotFoundErrorData = {
  error: operations.ErrorSchemaVersionNotFound;
};

/**
 * HTTP 404 response
 */
export class GetApiV1NodeTypesNotFoundError extends LinkageError {
  error: operations.ErrorSchemaVersionNotFound;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1NodeTypesNotFoundErrorData;

  constructor(
    err: GetApiV1NodeTypesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1NodeTypesNotFoundError";
  }
}

/** @internal */
export const GetApiV1FeaturesInternalServerError$inboundSchema: z.ZodType<
  GetApiV1FeaturesInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations
      .GetApiV1FeaturesErrorProjectHasAnInvalidConfiguration$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1FeaturesInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetApiV1FeaturesUnauthorizedError$inboundSchema: z.ZodType<
  GetApiV1FeaturesUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.GetApiV1FeaturesUnauthorizedError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1FeaturesUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetApiV1NodeTypesNotFoundError$inboundSchema: z.ZodType<
  GetApiV1NodeTypesNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorSchemaVersionNotFound$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1NodeTypesNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
