/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 400 response
 */
export type GetApiV1RunsBadRequestErrorData = {
  error: operations.GetApiV1RunsError;
};

/**
 * HTTP 400 response
 */
export class GetApiV1RunsBadRequestError extends LinkageError {
  error: operations.GetApiV1RunsError;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1RunsBadRequestErrorData;

  constructor(
    err: GetApiV1RunsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1RunsBadRequestError";
  }
}

/** @internal */
export const GetApiV1RunsBadRequestError$inboundSchema: z.ZodType<
  GetApiV1RunsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.GetApiV1RunsError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1RunsBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
