/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 404 response
 */
export type GetApiV1StateNotFoundErrorData = {
  error: operations.GetApiV1StateNotFoundError;
};

/**
 * HTTP 404 response
 */
export class GetApiV1StateNotFoundError extends LinkageError {
  error: operations.GetApiV1StateNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1StateNotFoundErrorData;

  constructor(
    err: GetApiV1StateNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1StateNotFoundError";
  }
}

/**
 * HTTP 400 response
 */
export type GetApiV1StateBadRequestErrorData = {
  error: operations.GetApiV1StateBadRequestError;
};

/**
 * HTTP 400 response
 */
export class GetApiV1StateBadRequestError extends LinkageError {
  error: operations.GetApiV1StateBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1StateBadRequestErrorData;

  constructor(
    err: GetApiV1StateBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1StateBadRequestError";
  }
}

/**
 * HTTP 400 response
 */
export type PostApiV1StateBadRequestErrorData = {
  error: operations.PostApiV1StateBadRequestError;
};

/**
 * HTTP 400 response
 */
export class PostApiV1StateBadRequestError extends LinkageError {
  error: operations.PostApiV1StateBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1StateBadRequestErrorData;

  constructor(
    err: PostApiV1StateBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1StateBadRequestError";
  }
}

/** @internal */
export const GetApiV1StateNotFoundError$inboundSchema: z.ZodType<
  GetApiV1StateNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.GetApiV1StateNotFoundError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1StateNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetApiV1StateNotFoundError$Outbound = {
  error: operations.GetApiV1StateNotFoundError$Outbound;
};

/** @internal */
export const GetApiV1StateNotFoundError$outboundSchema: z.ZodType<
  GetApiV1StateNotFoundError$Outbound,
  z.ZodTypeDef,
  GetApiV1StateNotFoundError
> = z.instanceof(GetApiV1StateNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.GetApiV1StateNotFoundError$outboundSchema),
  }));

/** @internal */
export const GetApiV1StateBadRequestError$inboundSchema: z.ZodType<
  GetApiV1StateBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.GetApiV1StateBadRequestError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1StateBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetApiV1StateBadRequestError$Outbound = {
  error: operations.GetApiV1StateBadRequestError$Outbound;
};

/** @internal */
export const GetApiV1StateBadRequestError$outboundSchema: z.ZodType<
  GetApiV1StateBadRequestError$Outbound,
  z.ZodTypeDef,
  GetApiV1StateBadRequestError
> = z.instanceof(GetApiV1StateBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.GetApiV1StateBadRequestError$outboundSchema),
  }));

/** @internal */
export const PostApiV1StateBadRequestError$inboundSchema: z.ZodType<
  PostApiV1StateBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.PostApiV1StateBadRequestError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1StateBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiV1StateBadRequestError$Outbound = {
  error: operations.PostApiV1StateBadRequestError$Outbound;
};

/** @internal */
export const PostApiV1StateBadRequestError$outboundSchema: z.ZodType<
  PostApiV1StateBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1StateBadRequestError
> = z.instanceof(PostApiV1StateBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1StateBadRequestError$outboundSchema
    ),
  }));
