/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 400 response
 */
export type GetApiV1RunsRunIdEventsBadRequestErrorData = {
  error: operations.GetApiV1RunsRunIdEventsError;
};

/**
 * HTTP 400 response
 */
export class GetApiV1RunsRunIdEventsBadRequestError extends LinkageError {
  error: operations.GetApiV1RunsRunIdEventsError;

  /** The original data that was passed to this error instance. */
  data$: GetApiV1RunsRunIdEventsBadRequestErrorData;

  constructor(
    err: GetApiV1RunsRunIdEventsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetApiV1RunsRunIdEventsBadRequestError";
  }
}

/** @internal */
export const GetApiV1RunsRunIdEventsBadRequestError$inboundSchema: z.ZodType<
  GetApiV1RunsRunIdEventsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.GetApiV1RunsRunIdEventsError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetApiV1RunsRunIdEventsBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetApiV1RunsRunIdEventsBadRequestError$Outbound = {
  error: operations.GetApiV1RunsRunIdEventsError$Outbound;
};

/** @internal */
export const GetApiV1RunsRunIdEventsBadRequestError$outboundSchema: z.ZodType<
  GetApiV1RunsRunIdEventsBadRequestError$Outbound,
  z.ZodTypeDef,
  GetApiV1RunsRunIdEventsBadRequestError
> = z.instanceof(GetApiV1RunsRunIdEventsBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.GetApiV1RunsRunIdEventsError$outboundSchema),
  }));
