/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 400 response
 */
export type PostApiV1RunsRunIdEventsBadRequestErrorData = {
  error: operations.PostApiV1RunsRunIdEventsError;
};

/**
 * HTTP 400 response
 */
export class PostApiV1RunsRunIdEventsBadRequestError extends LinkageError {
  error: operations.PostApiV1RunsRunIdEventsError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1RunsRunIdEventsBadRequestErrorData;

  constructor(
    err: PostApiV1RunsRunIdEventsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1RunsRunIdEventsBadRequestError";
  }
}

/** @internal */
export const PostApiV1RunsRunIdEventsBadRequestError$inboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.PostApiV1RunsRunIdEventsError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1RunsRunIdEventsBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiV1RunsRunIdEventsBadRequestError$Outbound = {
  error: operations.PostApiV1RunsRunIdEventsError$Outbound;
};

/** @internal */
export const PostApiV1RunsRunIdEventsBadRequestError$outboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1RunsRunIdEventsBadRequestError
> = z.instanceof(PostApiV1RunsRunIdEventsBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1RunsRunIdEventsError$outboundSchema
    ),
  }));
