/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * Validates the webhook trigger and starts a workflow execution.
 */
export type PostApiV1TriggerTriggerIdInternalServerErrorData = {
  error?: string | undefined;
  /**
   * Unknown type
   */
  details?: any | undefined;
};

/**
 * Validates the webhook trigger and starts a workflow execution.
 */
export class PostApiV1TriggerTriggerIdInternalServerError extends LinkageError {
  error?: string | undefined;
  /**
   * Unknown type
   */
  details?: any | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1TriggerTriggerIdInternalServerErrorData;

  constructor(
    err: PostApiV1TriggerTriggerIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.details != null) this.details = err.details;

    this.name = "PostApiV1TriggerTriggerIdInternalServerError";
  }
}

/**
 * HTTP 404 response
 */
export type PostApiV1TriggerTriggerIdNotFoundErrorData = {
  error: operations.PostApiV1TriggerTriggerIdNotFoundError;
};

/**
 * HTTP 404 response
 */
export class PostApiV1TriggerTriggerIdNotFoundError extends LinkageError {
  error: operations.PostApiV1TriggerTriggerIdNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1TriggerTriggerIdNotFoundErrorData;

  constructor(
    err: PostApiV1TriggerTriggerIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1TriggerTriggerIdNotFoundError";
  }
}

/**
 * HTTP 403 response
 */
export type ForbiddenErrorData = {
  error: operations.PostApiV1TriggerTriggerIdForbiddenError;
};

/**
 * HTTP 403 response
 */
export class ForbiddenError extends LinkageError {
  error: operations.PostApiV1TriggerTriggerIdForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorData;

  constructor(
    err: ForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ForbiddenError";
  }
}

/**
 * HTTP 401 response
 */
export type PostApiV1TriggerTriggerIdUnauthorizedErrorData = {
  error: operations.PostApiV1TriggerTriggerIdUnauthorizedError;
};

/**
 * HTTP 401 response
 */
export class PostApiV1TriggerTriggerIdUnauthorizedError extends LinkageError {
  error: operations.PostApiV1TriggerTriggerIdUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1TriggerTriggerIdUnauthorizedErrorData;

  constructor(
    err: PostApiV1TriggerTriggerIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1TriggerTriggerIdUnauthorizedError";
  }
}

/**
 * HTTP 400 response
 */
export type PostApiV1TriggerTriggerIdBadRequestErrorData = {
  error: operations.PostApiV1TriggerTriggerIdBadRequestError;
};

/**
 * HTTP 400 response
 */
export class PostApiV1TriggerTriggerIdBadRequestError extends LinkageError {
  error: operations.PostApiV1TriggerTriggerIdBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1TriggerTriggerIdBadRequestErrorData;

  constructor(
    err: PostApiV1TriggerTriggerIdBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1TriggerTriggerIdBadRequestError";
  }
}

/**
 * HTTP 401 response
 */
export type PostApiV1TriggerManualUnauthorizedErrorData = {
  error: operations.PostApiV1TriggerManualUnauthorizedError;
};

/**
 * HTTP 401 response
 */
export class PostApiV1TriggerManualUnauthorizedError extends LinkageError {
  error: operations.PostApiV1TriggerManualUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1TriggerManualUnauthorizedErrorData;

  constructor(
    err: PostApiV1TriggerManualUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1TriggerManualUnauthorizedError";
  }
}

/**
 * HTTP 400 response
 */
export type PostApiV1TriggerManualBadRequestErrorData = {
  error: operations.PostApiV1TriggerManualBadRequestError;
};

/**
 * HTTP 400 response
 */
export class PostApiV1TriggerManualBadRequestError extends LinkageError {
  error: operations.PostApiV1TriggerManualBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1TriggerManualBadRequestErrorData;

  constructor(
    err: PostApiV1TriggerManualBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1TriggerManualBadRequestError";
  }
}

/** @internal */
export const PostApiV1TriggerTriggerIdInternalServerError$inboundSchema:
  z.ZodType<
    PostApiV1TriggerTriggerIdInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    details: z.any().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PostApiV1TriggerTriggerIdInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type PostApiV1TriggerTriggerIdInternalServerError$Outbound = {
  error?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdInternalServerError$outboundSchema:
  z.ZodType<
    PostApiV1TriggerTriggerIdInternalServerError$Outbound,
    z.ZodTypeDef,
    PostApiV1TriggerTriggerIdInternalServerError
  > = z.instanceof(PostApiV1TriggerTriggerIdInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
      details: z.any().optional(),
    }));

/** @internal */
export const PostApiV1TriggerTriggerIdNotFoundError$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.PostApiV1TriggerTriggerIdNotFoundError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1TriggerTriggerIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiV1TriggerTriggerIdNotFoundError$Outbound = {
  error: operations.PostApiV1TriggerTriggerIdNotFoundError$Outbound;
};

/** @internal */
export const PostApiV1TriggerTriggerIdNotFoundError$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdNotFoundError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdNotFoundError
> = z.instanceof(PostApiV1TriggerTriggerIdNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1TriggerTriggerIdNotFoundError$outboundSchema
    ),
  }));

/** @internal */
export const ForbiddenError$inboundSchema: z.ZodType<
  ForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.PostApiV1TriggerTriggerIdForbiddenError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ForbiddenError$Outbound = {
  error: operations.PostApiV1TriggerTriggerIdForbiddenError$Outbound;
};

/** @internal */
export const ForbiddenError$outboundSchema: z.ZodType<
  ForbiddenError$Outbound,
  z.ZodTypeDef,
  ForbiddenError
> = z.instanceof(ForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1TriggerTriggerIdForbiddenError$outboundSchema
    ),
  }));

/** @internal */
export const PostApiV1TriggerTriggerIdUnauthorizedError$inboundSchema:
  z.ZodType<PostApiV1TriggerTriggerIdUnauthorizedError, z.ZodTypeDef, unknown> =
    z.object({
      error: z.lazy(() =>
        operations.PostApiV1TriggerTriggerIdUnauthorizedError$inboundSchema
      ),
      request$: z.instanceof(Request),
      response$: z.instanceof(Response),
      body$: z.string(),
    })
      .transform((v) => {
        return new PostApiV1TriggerTriggerIdUnauthorizedError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      });

/** @internal */
export type PostApiV1TriggerTriggerIdUnauthorizedError$Outbound = {
  error: operations.PostApiV1TriggerTriggerIdUnauthorizedError$Outbound;
};

/** @internal */
export const PostApiV1TriggerTriggerIdUnauthorizedError$outboundSchema:
  z.ZodType<
    PostApiV1TriggerTriggerIdUnauthorizedError$Outbound,
    z.ZodTypeDef,
    PostApiV1TriggerTriggerIdUnauthorizedError
  > = z.instanceof(PostApiV1TriggerTriggerIdUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.lazy(() =>
        operations.PostApiV1TriggerTriggerIdUnauthorizedError$outboundSchema
      ),
    }));

/** @internal */
export const PostApiV1TriggerTriggerIdBadRequestError$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.PostApiV1TriggerTriggerIdBadRequestError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1TriggerTriggerIdBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiV1TriggerTriggerIdBadRequestError$Outbound = {
  error: operations.PostApiV1TriggerTriggerIdBadRequestError$Outbound;
};

/** @internal */
export const PostApiV1TriggerTriggerIdBadRequestError$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdBadRequestError
> = z.instanceof(PostApiV1TriggerTriggerIdBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1TriggerTriggerIdBadRequestError$outboundSchema
    ),
  }));

/** @internal */
export const PostApiV1TriggerManualUnauthorizedError$inboundSchema: z.ZodType<
  PostApiV1TriggerManualUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.PostApiV1TriggerManualUnauthorizedError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1TriggerManualUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiV1TriggerManualUnauthorizedError$Outbound = {
  error: operations.PostApiV1TriggerManualUnauthorizedError$Outbound;
};

/** @internal */
export const PostApiV1TriggerManualUnauthorizedError$outboundSchema: z.ZodType<
  PostApiV1TriggerManualUnauthorizedError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualUnauthorizedError
> = z.instanceof(PostApiV1TriggerManualUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1TriggerManualUnauthorizedError$outboundSchema
    ),
  }));

/** @internal */
export const PostApiV1TriggerManualBadRequestError$inboundSchema: z.ZodType<
  PostApiV1TriggerManualBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.PostApiV1TriggerManualBadRequestError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1TriggerManualBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PostApiV1TriggerManualBadRequestError$Outbound = {
  error: operations.PostApiV1TriggerManualBadRequestError$Outbound;
};

/** @internal */
export const PostApiV1TriggerManualBadRequestError$outboundSchema: z.ZodType<
  PostApiV1TriggerManualBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualBadRequestError
> = z.instanceof(PostApiV1TriggerManualBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.PostApiV1TriggerManualBadRequestError$outboundSchema
    ),
  }));
