/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 500 response
 */
export type PostApiV1RunsInternalServerErrorData = {
  error: operations.ErrorFailedToCreateRun;
};

/**
 * HTTP 500 response
 */
export class PostApiV1RunsInternalServerError extends LinkageError {
  error: operations.ErrorFailedToCreateRun;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1RunsInternalServerErrorData;

  constructor(
    err: PostApiV1RunsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1RunsInternalServerError";
  }
}

/**
 * HTTP 400 response
 */
export type PostApiV1RunsBadRequestErrorData = {
  error: operations.ErrorInvalidRunPayload;
};

/**
 * HTTP 400 response
 */
export class PostApiV1RunsBadRequestError extends LinkageError {
  error: operations.ErrorInvalidRunPayload;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1RunsBadRequestErrorData;

  constructor(
    err: PostApiV1RunsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1RunsBadRequestError";
  }
}

/** @internal */
export const PostApiV1RunsInternalServerError$inboundSchema: z.ZodType<
  PostApiV1RunsInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorFailedToCreateRun$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1RunsInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostApiV1RunsBadRequestError$inboundSchema: z.ZodType<
  PostApiV1RunsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorInvalidRunPayload$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1RunsBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
