/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 500 response
 */
export type PostApiV1CreateInternalServerErrorData = {
  error: operations.ErrorFailedToCreateWorkflow;
};

/**
 * HTTP 500 response
 */
export class PostApiV1CreateInternalServerError extends LinkageError {
  error: operations.ErrorFailedToCreateWorkflow;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1CreateInternalServerErrorData;

  constructor(
    err: PostApiV1CreateInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1CreateInternalServerError";
  }
}

/**
 * HTTP 404 response
 */
export type PostApiV1CreateNotFoundErrorData = {
  error: operations.ErrorProjectNotFound;
};

/**
 * HTTP 404 response
 */
export class PostApiV1CreateNotFoundError extends LinkageError {
  error: operations.ErrorProjectNotFound;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1CreateNotFoundErrorData;

  constructor(
    err: PostApiV1CreateNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1CreateNotFoundError";
  }
}

/**
 * HTTP 400 response
 */
export type PostApiV1CreateBadRequestErrorData = {
  error: operations.PostApiV1CreateBadRequestError;
};

/**
 * HTTP 400 response
 */
export class PostApiV1CreateBadRequestError extends LinkageError {
  error: operations.PostApiV1CreateBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1CreateBadRequestErrorData;

  constructor(
    err: PostApiV1CreateBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1CreateBadRequestError";
  }
}

/** @internal */
export const PostApiV1CreateInternalServerError$inboundSchema: z.ZodType<
  PostApiV1CreateInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorFailedToCreateWorkflow$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1CreateInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostApiV1CreateNotFoundError$inboundSchema: z.ZodType<
  PostApiV1CreateNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.ErrorProjectNotFound$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1CreateNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostApiV1CreateBadRequestError$inboundSchema: z.ZodType<
  PostApiV1CreateBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.PostApiV1CreateBadRequestError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1CreateBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
