/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { LinkageError } from "./linkageerror.js";

/**
 * HTTP 500 response
 */
export type PostApiV1XInternalServerErrorData = {
  error: operations.PostApiV1XInternalServerErrorError;
};

/**
 * HTTP 500 response
 */
export class PostApiV1XInternalServerError extends LinkageError {
  error: operations.PostApiV1XInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1XInternalServerErrorData;

  constructor(
    err: PostApiV1XInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1XInternalServerError";
  }
}

/**
 * HTTP 429 response
 */
export type TooManyRequestsErrorData = {
  error: operations.TooManyRequestsError;
};

/**
 * HTTP 429 response
 */
export class TooManyRequestsError extends LinkageError {
  error: operations.TooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: TooManyRequestsErrorData;

  constructor(
    err: TooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "TooManyRequestsError";
  }
}

/**
 * HTTP 401 response
 */
export type PostApiV1XUnauthorizedErrorData = {
  error: operations.PostApiV1XUnauthorizedError;
};

/**
 * HTTP 401 response
 */
export class PostApiV1XUnauthorizedError extends LinkageError {
  error: operations.PostApiV1XUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: PostApiV1XUnauthorizedErrorData;

  constructor(
    err: PostApiV1XUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "PostApiV1XUnauthorizedError";
  }
}

/** @internal */
export const PostApiV1XInternalServerError$inboundSchema: z.ZodType<
  PostApiV1XInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.PostApiV1XInternalServerErrorError$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1XInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const TooManyRequestsError$inboundSchema: z.ZodType<
  TooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.TooManyRequestsError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new TooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostApiV1XUnauthorizedError$inboundSchema: z.ZodType<
  PostApiV1XUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.PostApiV1XUnauthorizedError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostApiV1XUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
