/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresGet } from "../../funcs/featuresGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1FeaturesRequest$inboundSchema.optional(),
};

export const tool$featuresGet: ToolDefinition<typeof args> = {
  name: "features-get",
  description: `Get project features

Returns enabled feature flags for the project, including billing-gated features.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await featuresGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
