/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { manualTriggerExecute } from "../../funcs/manualTriggerExecute.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1TriggerManualRequest$inboundSchema.optional(),
};

export const tool$manualTriggerExecute: ToolDefinition<typeof args> = {
  name: "manual-trigger-execute",
  description: `Execute a manual trigger

Executes a workflow on-demand using client credentials and an optional payload.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await manualTriggerExecute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
