/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodeOverlaysGet } from "../../funcs/nodeOverlaysGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1NodeOverlaysRequest$inboundSchema.optional(),
};

export const tool$nodeOverlaysGet: ToolDefinition<typeof args> = {
  name: "node-overlays-get",
  description: `Get node overlays

Returns node overlay metadata configured for a project.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nodeOverlaysGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
