/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsIngestEvents } from "../../funcs/runsIngestEvents.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1RunsRunIdEventsRequest$inboundSchema,
};

export const tool$runsIngestEvents: ToolDefinition<typeof args> = {
  name: "runs-ingest-events",
  description: `Ingest run events

Appends one or more events to the run event stream for the given run id.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runsIngestEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
