/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsGet } from "../../funcs/runsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1RunsRunIdRequest$inboundSchema,
};

export const tool$runsGet: ToolDefinition<typeof args> = {
  name: "runs-get",
  description: `Get a workflow run

Returns run metadata for the given run id.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
