/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsCreate } from "../../funcs/runsCreate.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$runsCreate: ToolDefinition = {
  name: "runs-create",
  description: `Create a workflow run

Creates a new run for the specified workflow and returns the run metadata.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await runsCreate(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
