/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsGetEvents } from "../../funcs/runsGetEvents.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1RunsRunIdEventsRequest$inboundSchema,
};

export const tool$runsGetEvents: ToolDefinition<typeof args> = {
  name: "runs-get-events",
  description: `List or stream run events

Returns run events for the given run id, with optional polling cursor or SSE streaming.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runsGetEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
