/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsList } from "../../funcs/runsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1RunsRequest$inboundSchema.optional(),
};

export const tool$runsList: ToolDefinition<typeof args> = {
  name: "runs-list",
  description: `List workflow runs

Returns recent runs for a workflow, with optional pagination.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
