/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stateOptions } from "../../funcs/stateOptions.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$stateOptions: ToolDefinition = {
  name: "state-options",
  description: `Preflight workflow state requests

Returns CORS headers for workflow state GET/POST requests.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await stateOptions(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
