/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stateUpdate } from "../../funcs/stateUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1StateRequest$inboundSchema.optional(),
};

export const tool$stateUpdate: ToolDefinition<typeof args> = {
  name: "state-update",
  description: `Update workflow state

Persists workflow nodes/edges when the payload hash changes.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await stateUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
