/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stateGet } from "../../funcs/stateGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1StateRequest$inboundSchema.optional(),
};

export const tool$stateGet: ToolDefinition<typeof args> = {
  name: "state-get",
  description: `Get workflow state

Fetches workflow nodes/edges and hashes for a workflow.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await stateGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
