/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { triggerGetDetails } from "../../funcs/triggerGetDetails.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiV1TriggerTriggerIdRequest$inboundSchema,
};

export const tool$triggerGetDetails: ToolDefinition<typeof args> = {
  name: "trigger-get-details",
  description: `Get trigger details

Returns metadata about a trigger for testing or debugging.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggerGetDetails(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
