/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { triggerExecute } from "../../funcs/triggerExecute.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1TriggerTriggerIdRequest$inboundSchema,
};

export const tool$triggerExecute: ToolDefinition<typeof args> = {
  name: "trigger-execute",
  description: `Execute a webhook trigger

Validates the webhook trigger and starts a workflow execution.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggerExecute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
