/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsCreate } from "../../funcs/workflowsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1CreateRequest$inboundSchema.optional(),
};

export const tool$workflowsCreate: ToolDefinition<typeof args> = {
  name: "workflows-create",
  description: `Create a workflow

Creates a workflow for a project with the provided nodes and edges.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workflowsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
