/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowExecute } from "../../funcs/workflowExecute.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1XRequest$inboundSchema.optional(),
};

export const tool$workflowExecute: ToolDefinition<typeof args> = {
  name: "workflow-execute",
  description: `Execute a workflow run

Validates client credentials and schema version, persists execution state, forwards the payload to the deployed app, and returns the execution id.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workflowExecute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
