/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { LinkageCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$featuresGet } from "./tools/featuresGet.js";
import { tool$manualTriggerExecute } from "./tools/manualTriggerExecute.js";
import { tool$nodeOverlaysGet } from "./tools/nodeOverlaysGet.js";
import { tool$nodeTypesGet } from "./tools/nodeTypesGet.js";
import { tool$runsCreate } from "./tools/runsCreate.js";
import { tool$runsGet } from "./tools/runsGet.js";
import { tool$runsGetEvents } from "./tools/runsGetEvents.js";
import { tool$runsIngestEvents } from "./tools/runsIngestEvents.js";
import { tool$runsList } from "./tools/runsList.js";
import { tool$stateGet } from "./tools/stateGet.js";
import { tool$stateOptions } from "./tools/stateOptions.js";
import { tool$stateUpdate } from "./tools/stateUpdate.js";
import { tool$triggerExecute } from "./tools/triggerExecute.js";
import { tool$triggerGetDetails } from "./tools/triggerGetDetails.js";
import { tool$workflowExecute } from "./tools/workflowExecute.js";
import { tool$workflowsCreate } from "./tools/workflowsCreate.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Linkage",
    version: "0.6.0",
  });

  const client = new LinkageCore({
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$workflowsCreate);
  tool(tool$featuresGet);
  tool(tool$nodeOverlaysGet);
  tool(tool$nodeTypesGet);
  tool(tool$runsList);
  tool(tool$runsCreate);
  tool(tool$runsGet);
  tool(tool$runsGetEvents);
  tool(tool$runsIngestEvents);
  tool(tool$stateOptions);
  tool(tool$stateGet);
  tool(tool$stateUpdate);
  tool(tool$workflowExecute);
  tool(tool$triggerExecute);
  tool(tool$triggerGetDetails);
  tool(tool$manualTriggerExecute);

  return server;
}
