/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresGet } from "../funcs/featuresGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Features extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetApiV1FeaturesResponse | undefined> {
    return unwrapAsync(featuresGet(
      this,
      options,
    ));
  }
}
