/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresGet } from "../funcs/featuresGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Features extends ClientSDK {
  /**
   * Get project features
   *
   * @remarks
   * Returns enabled feature flags for the project, including billing-gated features.
   */
  async get(
    request?: operations.GetApiV1FeaturesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetApiV1FeaturesResponse> {
    return unwrapAsync(featuresGet(
      this,
      request,
      options,
    ));
  }
}
