/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { manualTriggerExecute } from "../funcs/manualTriggerExecute.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ManualTrigger extends ClientSDK {
  /**
   * Execute a manual trigger
   *
   * @remarks
   * Executes a workflow on-demand using client credentials and an optional payload.
   */
  async execute(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1TriggerManualResponse> {
    return unwrapAsync(manualTriggerExecute(
      this,
      options,
    ));
  }
}
