/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodeTypesGet } from "../funcs/nodeTypesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NodeTypes extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetApiV1NodeTypesResponse | undefined> {
    return unwrapAsync(nodeTypesGet(
      this,
      options,
    ));
  }
}
