/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodeOverlaysGet } from "../funcs/nodeOverlaysGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NodeOverlays extends ClientSDK {
  /**
   * Get node overlays
   *
   * @remarks
   * Returns node overlay metadata configured for a project.
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetApiV1NodeOverlaysResponse> {
    return unwrapAsync(nodeOverlaysGet(
      this,
      options,
    ));
  }
}
