/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodeTypesGet } from "../funcs/nodeTypesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class NodeTypes extends ClientSDK {
  /**
   * Get node types
   *
   * @remarks
   * Returns the available node types for the project, optionally narrowed by schema version.
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetApiV1NodeTypesResponse> {
    return unwrapAsync(nodeTypesGet(
      this,
      options,
    ));
  }
}
