/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nodesGetOverlays } from "../funcs/nodesGetOverlays.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Nodes extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async getOverlays(
    options?: RequestOptions,
  ): Promise<operations.GetApiV1NodeOverlaysResponse | undefined> {
    return unwrapAsync(nodesGetOverlays(
      this,
      options,
    ));
  }
}
