/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { resourcesCreate } from "../funcs/resourcesCreate.js";
import { resourcesPostX } from "../funcs/resourcesPostX.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Resources extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async create(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(resourcesCreate(
      this,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async postX(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1XResponse> {
    return unwrapAsync(resourcesPostX(
      this,
      options,
    ));
  }
}
