/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsCreate } from "../funcs/runsCreate.js";
import { runsGet } from "../funcs/runsGet.js";
import { runsGetEvents } from "../funcs/runsGetEvents.js";
import { runsIngestEvents } from "../funcs/runsIngestEvents.js";
import { runsList } from "../funcs/runsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Runs extends ClientSDK {
  /**
   * List workflow runs
   *
   * @remarks
   * Returns recent runs for a workflow, with optional pagination.
   */
  async list(
    request?: operations.GetApiV1RunsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetApiV1RunsResponse> {
    return unwrapAsync(runsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a workflow run
   *
   * @remarks
   * Creates a new run for the specified workflow and returns the run metadata.
   */
  async create(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1RunsResponse> {
    return unwrapAsync(runsCreate(
      this,
      options,
    ));
  }

  /**
   * Get a workflow run
   *
   * @remarks
   * Returns run metadata for the given run id.
   */
  async get(
    request: operations.GetApiV1RunsRunIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiV1RunsRunIdResponse> {
    return unwrapAsync(runsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * List or stream run events
   *
   * @remarks
   * Returns run events for the given run id, with optional polling cursor or SSE streaming.
   */
  async getEvents(
    request: operations.GetApiV1RunsRunIdEventsRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(runsGetEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Ingest run events
   *
   * @remarks
   * Appends one or more events to the run event stream for the given run id.
   */
  async ingestEvents(
    request: operations.PostApiV1RunsRunIdEventsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostApiV1RunsRunIdEventsResponse> {
    return unwrapAsync(runsIngestEvents(
      this,
      request,
      options,
    ));
  }
}
