/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Features } from "./features.js";
import { Nodes } from "./nodes.js";
import { NodeTypes } from "./nodetypes.js";
import { Resources } from "./resources.js";
import { State } from "./state.js";
import { Triggers } from "./triggers.js";

export class Linkage extends ClientSDK {
  private _resources?: Resources;
  get resources(): Resources {
    return (this._resources ??= new Resources(this._options));
  }

  private _features?: Features;
  get features(): Features {
    return (this._features ??= new Features(this._options));
  }

  private _nodes?: Nodes;
  get nodes(): Nodes {
    return (this._nodes ??= new Nodes(this._options));
  }

  private _nodeTypes?: NodeTypes;
  get nodeTypes(): NodeTypes {
    return (this._nodeTypes ??= new NodeTypes(this._options));
  }

  private _state?: State;
  get state(): State {
    return (this._state ??= new State(this._options));
  }

  private _triggers?: Triggers;
  get triggers(): Triggers {
    return (this._triggers ??= new Triggers(this._options));
  }
}
