/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getApiV1State } from "../funcs/getApiV1State.js";
import { postApiV1Create } from "../funcs/postApiV1Create.js";
import { postApiV1State } from "../funcs/postApiV1State.js";
import { postApiV1X } from "../funcs/postApiV1X.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Linkage extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async postApiV1Create(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(postApiV1Create(
      this,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async getApiV1State(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(getApiV1State(
      this,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async postApiV1State(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(postApiV1State(
      this,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async postApiV1X(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1XResponse> {
    return unwrapAsync(postApiV1X(
      this,
      options,
    ));
  }
}
