/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stateGet } from "../funcs/stateGet.js";
import { stateOptions } from "../funcs/stateOptions.js";
import { stateUpdate } from "../funcs/stateUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class State extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async options(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(stateOptions(
      this,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetApiV1StateResponse> {
    return unwrapAsync(stateGet(
      this,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async update(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1StateResponse> {
    return unwrapAsync(stateUpdate(
      this,
      options,
    ));
  }
}
