/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { stateGet } from "../funcs/stateGet.js";
import { stateOptions } from "../funcs/stateOptions.js";
import { stateUpdate } from "../funcs/stateUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class State extends ClientSDK {
  /**
   * Preflight workflow state requests
   *
   * @remarks
   * Returns CORS headers for workflow state GET/POST requests.
   */
  async options(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(stateOptions(
      this,
      options,
    ));
  }

  /**
   * Get workflow state
   *
   * @remarks
   * Fetches workflow nodes/edges and hashes for a workflow.
   */
  async get(
    request?: operations.GetApiV1StateRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetApiV1StateResponse> {
    return unwrapAsync(stateGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update workflow state
   *
   * @remarks
   * Persists workflow nodes/edges when the payload hash changes.
   */
  async update(
    request?: operations.PostApiV1StateRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostApiV1StateResponse | undefined> {
    return unwrapAsync(stateUpdate(
      this,
      request,
      options,
    ));
  }
}
