/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { triggerExecute } from "../funcs/triggerExecute.js";
import { triggerGetDetails } from "../funcs/triggerGetDetails.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Trigger extends ClientSDK {
  /**
   * Execute a webhook trigger
   *
   * @remarks
   * Validates the webhook trigger and starts a workflow execution.
   */
  async execute(
    request: operations.PostApiV1TriggerTriggerIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PostApiV1TriggerTriggerIdResponse> {
    return unwrapAsync(triggerExecute(
      this,
      request,
      options,
    ));
  }

  /**
   * Get trigger details
   *
   * @remarks
   * Returns metadata about a trigger for testing or debugging.
   */
  async getDetails(
    request: operations.GetApiV1TriggerTriggerIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiV1TriggerTriggerIdResponse> {
    return unwrapAsync(triggerGetDetails(
      this,
      request,
      options,
    ));
  }
}
