/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { triggersExecuteById } from "../funcs/triggersExecuteById.js";
import { triggersGetById } from "../funcs/triggersGetById.js";
import { triggersManual } from "../funcs/triggersManual.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Triggers extends ClientSDK {
  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async executeById(
    request: operations.PostApiV1TriggerTriggerIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PostApiV1TriggerTriggerIdResponse | undefined> {
    return unwrapAsync(triggersExecuteById(
      this,
      request,
      options,
    ));
  }

  /**
   * use to set the summary
   *
   * @remarks
   * use jsdoc tag to set the description
   */
  async getById(
    request: operations.GetApiV1TriggerTriggerIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiV1TriggerTriggerIdResponse | undefined> {
    return unwrapAsync(triggersGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Manual trigger endpoint for executing workflows on-demand
   *
   * @remarks
   * This endpoint requires authentication via client credentials
   */
  async manual(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1TriggerManualResponse | undefined> {
    return unwrapAsync(triggersManual(
      this,
      options,
    ));
  }
}
