/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowExecute } from "../funcs/workflowExecute.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Workflow extends ClientSDK {
  /**
   * Execute a workflow run
   *
   * @remarks
   * Validates client credentials and schema version, persists execution state, forwards the payload to the deployed app, and returns the execution id.
   */
  async execute(
    request?: operations.PostApiV1XRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostApiV1XResponse> {
    return unwrapAsync(workflowExecute(
      this,
      request,
      options,
    ));
  }
}
