/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsCreate } from "../funcs/workflowsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Workflows extends ClientSDK {
  /**
   * Create a workflow
   *
   * @remarks
   * Creates a workflow for a project with the provided nodes and edges.
   */
  async create(
    options?: RequestOptions,
  ): Promise<operations.PostApiV1CreateResponse> {
    return unwrapAsync(workflowsCreate(
      this,
      options,
    ));
  }
}
