/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @linkage-open/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx postApiV1Create.example.ts
 */

import { Linkage } from "@linkage-open/sdk";

const linkage = new Linkage();

async function main() {
  await linkage.postApiV1Create();
}

main().catch(console.error);
