/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1RunsRequest = {
  workflowId?: string | undefined;
  limit?: string | undefined;
};

export const GetApiV1RunsMessage = {
  WorkflowIdIsRequired: "workflowId is required",
} as const;
export type GetApiV1RunsMessage = ClosedEnum<typeof GetApiV1RunsMessage>;

export type GetApiV1RunsError = {
  message?: GetApiV1RunsMessage | undefined;
  details?: any | undefined;
};

/**
 * Returns recent runs for a workflow, with optional pagination.
 */
export type GetApiV1RunsResponse = {
  runs?: any | undefined;
};

/** @internal */
export type GetApiV1RunsRequest$Outbound = {
  workflowId?: string | undefined;
  limit?: string | undefined;
};

/** @internal */
export const GetApiV1RunsRequest$outboundSchema: z.ZodType<
  GetApiV1RunsRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1RunsRequest
> = z.object({
  workflowId: z.string().optional(),
  limit: z.string().optional(),
});

export function getApiV1RunsRequestToJSON(
  getApiV1RunsRequest: GetApiV1RunsRequest,
): string {
  return JSON.stringify(
    GetApiV1RunsRequest$outboundSchema.parse(getApiV1RunsRequest),
  );
}

/** @internal */
export const GetApiV1RunsMessage$inboundSchema: z.ZodNativeEnum<
  typeof GetApiV1RunsMessage
> = z.nativeEnum(GetApiV1RunsMessage);

/** @internal */
export const GetApiV1RunsError$inboundSchema: z.ZodType<
  GetApiV1RunsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: GetApiV1RunsMessage$inboundSchema.optional(),
  details: z.any().optional(),
});

export function getApiV1RunsErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1RunsError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1RunsError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1RunsError' from JSON`,
  );
}

/** @internal */
export const GetApiV1RunsResponse$inboundSchema: z.ZodType<
  GetApiV1RunsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  runs: z.any().optional(),
});

export function getApiV1RunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1RunsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1RunsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1RunsResponse' from JSON`,
  );
}
