/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1TriggerTriggerIdRequest = {
  triggerId: string;
};

/**
 * TODO: grab this from jsdoc and add a default
 */
export type GetApiV1TriggerTriggerIdResponse = {
  /**
   * TODO: This is an unknown type
   */
  id?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  name?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  type?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  enabled?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  workflowId?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  workflowName?: any | null | undefined;
};

/** @internal */
export const GetApiV1TriggerTriggerIdRequest$inboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  triggerId: z.string(),
});

/** @internal */
export type GetApiV1TriggerTriggerIdRequest$Outbound = {
  triggerId: string;
};

/** @internal */
export const GetApiV1TriggerTriggerIdRequest$outboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1TriggerTriggerIdRequest
> = z.object({
  triggerId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1TriggerTriggerIdRequest$ {
  /** @deprecated use `GetApiV1TriggerTriggerIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiV1TriggerTriggerIdRequest$inboundSchema;
  /** @deprecated use `GetApiV1TriggerTriggerIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiV1TriggerTriggerIdRequest$outboundSchema;
  /** @deprecated use `GetApiV1TriggerTriggerIdRequest$Outbound` instead. */
  export type Outbound = GetApiV1TriggerTriggerIdRequest$Outbound;
}

export function getApiV1TriggerTriggerIdRequestToJSON(
  getApiV1TriggerTriggerIdRequest: GetApiV1TriggerTriggerIdRequest,
): string {
  return JSON.stringify(
    GetApiV1TriggerTriggerIdRequest$outboundSchema.parse(
      getApiV1TriggerTriggerIdRequest,
    ),
  );
}

export function getApiV1TriggerTriggerIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1TriggerTriggerIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1TriggerTriggerIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1TriggerTriggerIdRequest' from JSON`,
  );
}

/** @internal */
export const GetApiV1TriggerTriggerIdResponse$inboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.any()).optional(),
  name: z.nullable(z.any()).optional(),
  type: z.nullable(z.any()).optional(),
  enabled: z.nullable(z.any()).optional(),
  workflowId: z.nullable(z.any()).optional(),
  workflowName: z.nullable(z.any()).optional(),
});

/** @internal */
export type GetApiV1TriggerTriggerIdResponse$Outbound = {
  id?: any | null | undefined;
  name?: any | null | undefined;
  type?: any | null | undefined;
  enabled?: any | null | undefined;
  workflowId?: any | null | undefined;
  workflowName?: any | null | undefined;
};

/** @internal */
export const GetApiV1TriggerTriggerIdResponse$outboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdResponse$Outbound,
  z.ZodTypeDef,
  GetApiV1TriggerTriggerIdResponse
> = z.object({
  id: z.nullable(z.any()).optional(),
  name: z.nullable(z.any()).optional(),
  type: z.nullable(z.any()).optional(),
  enabled: z.nullable(z.any()).optional(),
  workflowId: z.nullable(z.any()).optional(),
  workflowName: z.nullable(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiV1TriggerTriggerIdResponse$ {
  /** @deprecated use `GetApiV1TriggerTriggerIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetApiV1TriggerTriggerIdResponse$inboundSchema;
  /** @deprecated use `GetApiV1TriggerTriggerIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetApiV1TriggerTriggerIdResponse$outboundSchema;
  /** @deprecated use `GetApiV1TriggerTriggerIdResponse$Outbound` instead. */
  export type Outbound = GetApiV1TriggerTriggerIdResponse$Outbound;
}

export function getApiV1TriggerTriggerIdResponseToJSON(
  getApiV1TriggerTriggerIdResponse: GetApiV1TriggerTriggerIdResponse,
): string {
  return JSON.stringify(
    GetApiV1TriggerTriggerIdResponse$outboundSchema.parse(
      getApiV1TriggerTriggerIdResponse,
    ),
  );
}

export function getApiV1TriggerTriggerIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1TriggerTriggerIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1TriggerTriggerIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1TriggerTriggerIdResponse' from JSON`,
  );
}
