/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1RunsRunIdEventsRequest = {
  cursor?: string | undefined;
  limit?: string | undefined;
  stream?: string | undefined;
  runId: string;
};

export const GetApiV1RunsRunIdEventsMessage = {
  InvalidCursor: "Invalid cursor",
} as const;
export type GetApiV1RunsRunIdEventsMessage = ClosedEnum<
  typeof GetApiV1RunsRunIdEventsMessage
>;

export type GetApiV1RunsRunIdEventsError = {
  message?: GetApiV1RunsRunIdEventsMessage | undefined;
  details?: any | undefined;
};

/** @internal */
export type GetApiV1RunsRunIdEventsRequest$Outbound = {
  cursor?: string | undefined;
  limit?: string | undefined;
  stream?: string | undefined;
  runId: string;
};

/** @internal */
export const GetApiV1RunsRunIdEventsRequest$outboundSchema: z.ZodType<
  GetApiV1RunsRunIdEventsRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1RunsRunIdEventsRequest
> = z.object({
  cursor: z.string().optional(),
  limit: z.string().optional(),
  stream: z.string().optional(),
  runId: z.string(),
});

export function getApiV1RunsRunIdEventsRequestToJSON(
  getApiV1RunsRunIdEventsRequest: GetApiV1RunsRunIdEventsRequest,
): string {
  return JSON.stringify(
    GetApiV1RunsRunIdEventsRequest$outboundSchema.parse(
      getApiV1RunsRunIdEventsRequest,
    ),
  );
}

/** @internal */
export const GetApiV1RunsRunIdEventsMessage$inboundSchema: z.ZodNativeEnum<
  typeof GetApiV1RunsRunIdEventsMessage
> = z.nativeEnum(GetApiV1RunsRunIdEventsMessage);

/** @internal */
export const GetApiV1RunsRunIdEventsError$inboundSchema: z.ZodType<
  GetApiV1RunsRunIdEventsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: GetApiV1RunsRunIdEventsMessage$inboundSchema.optional(),
  details: z.any().optional(),
});

export function getApiV1RunsRunIdEventsErrorFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1RunsRunIdEventsError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1RunsRunIdEventsError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1RunsRunIdEventsError' from JSON`,
  );
}
