/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1TriggerTriggerIdRequest = {
  triggerId: string;
};

export const MessageTriggerNotFound = {
  TriggerNotFound: "Trigger not found",
} as const;
export type MessageTriggerNotFound = ClosedEnum<typeof MessageTriggerNotFound>;

export type ErrorTriggerNotFound = {
  message?: MessageTriggerNotFound | undefined;
  details?: any | undefined;
};

export const MessageTriggerIDIsRequired = {
  TriggerIDIsRequired: "Trigger ID is required",
} as const;
export type MessageTriggerIDIsRequired = ClosedEnum<
  typeof MessageTriggerIDIsRequired
>;

export type ErrorTriggerIDIsRequired = {
  message?: MessageTriggerIDIsRequired | undefined;
  details?: any | undefined;
};

/**
 * Returns metadata about a trigger for testing or debugging.
 */
export type GetApiV1TriggerTriggerIdResponse = {
  /**
   * Unknown type
   */
  id?: any | undefined;
  /**
   * Unknown type
   */
  name?: any | undefined;
  /**
   * Unknown type
   */
  type?: any | undefined;
  /**
   * Unknown type
   */
  enabled?: any | undefined;
  /**
   * Unknown type
   */
  workflowId?: any | undefined;
  /**
   * Unknown type
   */
  workflowName?: any | undefined;
};

/** @internal */
export type GetApiV1TriggerTriggerIdRequest$Outbound = {
  triggerId: string;
};

/** @internal */
export const GetApiV1TriggerTriggerIdRequest$outboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1TriggerTriggerIdRequest
> = z.object({
  triggerId: z.string(),
});

export function getApiV1TriggerTriggerIdRequestToJSON(
  getApiV1TriggerTriggerIdRequest: GetApiV1TriggerTriggerIdRequest,
): string {
  return JSON.stringify(
    GetApiV1TriggerTriggerIdRequest$outboundSchema.parse(
      getApiV1TriggerTriggerIdRequest,
    ),
  );
}

/** @internal */
export const MessageTriggerNotFound$inboundSchema: z.ZodNativeEnum<
  typeof MessageTriggerNotFound
> = z.nativeEnum(MessageTriggerNotFound);

/** @internal */
export const ErrorTriggerNotFound$inboundSchema: z.ZodType<
  ErrorTriggerNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageTriggerNotFound$inboundSchema.optional(),
  details: z.any().optional(),
});

export function errorTriggerNotFoundFromJSON(
  jsonString: string,
): SafeParseResult<ErrorTriggerNotFound, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorTriggerNotFound$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorTriggerNotFound' from JSON`,
  );
}

/** @internal */
export const MessageTriggerIDIsRequired$inboundSchema: z.ZodNativeEnum<
  typeof MessageTriggerIDIsRequired
> = z.nativeEnum(MessageTriggerIDIsRequired);

/** @internal */
export const ErrorTriggerIDIsRequired$inboundSchema: z.ZodType<
  ErrorTriggerIDIsRequired,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageTriggerIDIsRequired$inboundSchema.optional(),
  details: z.any().optional(),
});

export function errorTriggerIDIsRequiredFromJSON(
  jsonString: string,
): SafeParseResult<ErrorTriggerIDIsRequired, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorTriggerIDIsRequired$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorTriggerIDIsRequired' from JSON`,
  );
}

/** @internal */
export const GetApiV1TriggerTriggerIdResponse$inboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.any().optional(),
  name: z.any().optional(),
  type: z.any().optional(),
  enabled: z.any().optional(),
  workflowId: z.any().optional(),
  workflowName: z.any().optional(),
});

export function getApiV1TriggerTriggerIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1TriggerTriggerIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1TriggerTriggerIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1TriggerTriggerIdResponse' from JSON`,
  );
}
