/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1RunsRunIdRequest = {
  runId: string;
};

/**
 * Returns run metadata for the given run id.
 */
export type GetApiV1RunsRunIdResponse = {
  runId?: any | undefined;
  /**
   * Circular type
   */
  workflowId?: any | undefined;
  /**
   * Circular type
   */
  status?: any | undefined;
  /**
   * Circular type
   */
  nodeStatuses?: any | undefined;
  /**
   * Circular type
   */
  startedAt?: any | undefined;
  /**
   * Circular type
   */
  finishedAt?: any | undefined;
  /**
   * Circular type
   */
  metadata?: any | undefined;
  /**
   * Circular type
   */
  lastEventId?: any | undefined;
};

/** @internal */
export const GetApiV1RunsRunIdRequest$inboundSchema: z.ZodType<
  GetApiV1RunsRunIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  runId: z.string(),
});
/** @internal */
export type GetApiV1RunsRunIdRequest$Outbound = {
  runId: string;
};

/** @internal */
export const GetApiV1RunsRunIdRequest$outboundSchema: z.ZodType<
  GetApiV1RunsRunIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1RunsRunIdRequest
> = z.object({
  runId: z.string(),
});

export function getApiV1RunsRunIdRequestToJSON(
  getApiV1RunsRunIdRequest: GetApiV1RunsRunIdRequest,
): string {
  return JSON.stringify(
    GetApiV1RunsRunIdRequest$outboundSchema.parse(getApiV1RunsRunIdRequest),
  );
}
export function getApiV1RunsRunIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1RunsRunIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1RunsRunIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1RunsRunIdRequest' from JSON`,
  );
}

/** @internal */
export const GetApiV1RunsRunIdResponse$inboundSchema: z.ZodType<
  GetApiV1RunsRunIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  runId: z.any().optional(),
  workflowId: z.any().optional(),
  status: z.any().optional(),
  nodeStatuses: z.any().optional(),
  startedAt: z.any().optional(),
  finishedAt: z.any().optional(),
  metadata: z.any().optional(),
  lastEventId: z.any().optional(),
});
/** @internal */
export type GetApiV1RunsRunIdResponse$Outbound = {
  runId?: any | undefined;
  workflowId?: any | undefined;
  status?: any | undefined;
  nodeStatuses?: any | undefined;
  startedAt?: any | undefined;
  finishedAt?: any | undefined;
  metadata?: any | undefined;
  lastEventId?: any | undefined;
};

/** @internal */
export const GetApiV1RunsRunIdResponse$outboundSchema: z.ZodType<
  GetApiV1RunsRunIdResponse$Outbound,
  z.ZodTypeDef,
  GetApiV1RunsRunIdResponse
> = z.object({
  runId: z.any().optional(),
  workflowId: z.any().optional(),
  status: z.any().optional(),
  nodeStatuses: z.any().optional(),
  startedAt: z.any().optional(),
  finishedAt: z.any().optional(),
  metadata: z.any().optional(),
  lastEventId: z.any().optional(),
});

export function getApiV1RunsRunIdResponseToJSON(
  getApiV1RunsRunIdResponse: GetApiV1RunsRunIdResponse,
): string {
  return JSON.stringify(
    GetApiV1RunsRunIdResponse$outboundSchema.parse(getApiV1RunsRunIdResponse),
  );
}
export function getApiV1RunsRunIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1RunsRunIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1RunsRunIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1RunsRunIdResponse' from JSON`,
  );
}
