/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1NodeOverlaysRequest = {
  xClientId?: string | undefined;
  xClientSecret?: string | undefined;
};

/**
 * Returns node overlay metadata configured for a project.
 */
export type GetApiV1NodeOverlaysResponse = {
  overlays?: any | undefined;
};

/** @internal */
export type GetApiV1NodeOverlaysRequest$Outbound = {
  "x-client-id"?: string | undefined;
  "x-client-secret"?: string | undefined;
};

/** @internal */
export const GetApiV1NodeOverlaysRequest$outboundSchema: z.ZodType<
  GetApiV1NodeOverlaysRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1NodeOverlaysRequest
> = z.object({
  xClientId: z.string().optional(),
  xClientSecret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xClientId: "x-client-id",
    xClientSecret: "x-client-secret",
  });
});

export function getApiV1NodeOverlaysRequestToJSON(
  getApiV1NodeOverlaysRequest: GetApiV1NodeOverlaysRequest,
): string {
  return JSON.stringify(
    GetApiV1NodeOverlaysRequest$outboundSchema.parse(
      getApiV1NodeOverlaysRequest,
    ),
  );
}

/** @internal */
export const GetApiV1NodeOverlaysResponse$inboundSchema: z.ZodType<
  GetApiV1NodeOverlaysResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  overlays: z.any().optional(),
});

export function getApiV1NodeOverlaysResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1NodeOverlaysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1NodeOverlaysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1NodeOverlaysResponse' from JSON`,
  );
}
