/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiV1TriggerTriggerIdRequest = {
  triggerId: string;
};

/**
 * TODO: grab this from jsdoc and add a default
 */
export type GetApiV1TriggerTriggerIdResponse = {
  /**
   * TODO: This is an unknown type
   */
  id?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  name?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  type?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  enabled?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  workflowId?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  workflowName?: any | null | undefined;
};

/** @internal */
export type GetApiV1TriggerTriggerIdRequest$Outbound = {
  triggerId: string;
};

/** @internal */
export const GetApiV1TriggerTriggerIdRequest$outboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiV1TriggerTriggerIdRequest
> = z.object({
  triggerId: z.string(),
});

export function getApiV1TriggerTriggerIdRequestToJSON(
  getApiV1TriggerTriggerIdRequest: GetApiV1TriggerTriggerIdRequest,
): string {
  return JSON.stringify(
    GetApiV1TriggerTriggerIdRequest$outboundSchema.parse(
      getApiV1TriggerTriggerIdRequest,
    ),
  );
}

/** @internal */
export const GetApiV1TriggerTriggerIdResponse$inboundSchema: z.ZodType<
  GetApiV1TriggerTriggerIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.any()).optional(),
  name: z.nullable(z.any()).optional(),
  type: z.nullable(z.any()).optional(),
  enabled: z.nullable(z.any()).optional(),
  workflowId: z.nullable(z.any()).optional(),
  workflowName: z.nullable(z.any()).optional(),
});

export function getApiV1TriggerTriggerIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiV1TriggerTriggerIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiV1TriggerTriggerIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiV1TriggerTriggerIdResponse' from JSON`,
  );
}
