/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * TODO: grab this from jsdoc and add a default
 */
export type PostApiV1XResponse = {
  /**
   * TODO: This is an unknown type
   */
  executionId?: any | null | undefined;
};

/** @internal */
export const PostApiV1XResponse$inboundSchema: z.ZodType<
  PostApiV1XResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  executionId: z.nullable(z.any()).optional(),
});

export function postApiV1XResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1XResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1XResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1XResponse' from JSON`,
  );
}
