/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1CreateRequest = {
  xAppId?: string | undefined;
  xAppSecret?: string | undefined;
};

export const MessageFailedToCreateWorkflow = {
  FailedToCreateWorkflow: "Failed to create workflow",
} as const;
export type MessageFailedToCreateWorkflow = ClosedEnum<
  typeof MessageFailedToCreateWorkflow
>;

export type ErrorFailedToCreateWorkflow = {
  message?: MessageFailedToCreateWorkflow | undefined;
  details?: any | undefined;
};

export const MessageProjectNotFound = {
  ProjectNotFound: "Project not found",
} as const;
export type MessageProjectNotFound = ClosedEnum<typeof MessageProjectNotFound>;

export type ErrorProjectNotFound = {
  message?: MessageProjectNotFound | undefined;
  details?: any | undefined;
};

export const PostApiV1CreateBadRequestMessage = {
  MissingRequiredHeaders: "Missing required headers",
  WorkflowMustHaveAtLeastOneNodeAndOneEdge:
    "Workflow must have at least one node and one edge",
} as const;
export type PostApiV1CreateBadRequestMessage = ClosedEnum<
  typeof PostApiV1CreateBadRequestMessage
>;

export type PostApiV1CreateBadRequestError = {
  message?: PostApiV1CreateBadRequestMessage | undefined;
  details?: any | undefined;
};

/**
 * Creates a workflow for a project with the provided nodes and edges.
 */
export type PostApiV1CreateResponse = {
  /**
   * Unknown type
   */
  workflow?: any | undefined;
  /**
   * Unknown type
   */
  nodes?: any | undefined;
  /**
   * Unknown type
   */
  edges?: any | undefined;
};

/** @internal */
export type PostApiV1CreateRequest$Outbound = {
  "x-app-id"?: string | undefined;
  "x-app-secret"?: string | undefined;
};

/** @internal */
export const PostApiV1CreateRequest$outboundSchema: z.ZodType<
  PostApiV1CreateRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1CreateRequest
> = z.object({
  xAppId: z.string().optional(),
  xAppSecret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xAppId: "x-app-id",
    xAppSecret: "x-app-secret",
  });
});

export function postApiV1CreateRequestToJSON(
  postApiV1CreateRequest: PostApiV1CreateRequest,
): string {
  return JSON.stringify(
    PostApiV1CreateRequest$outboundSchema.parse(postApiV1CreateRequest),
  );
}

/** @internal */
export const MessageFailedToCreateWorkflow$inboundSchema: z.ZodNativeEnum<
  typeof MessageFailedToCreateWorkflow
> = z.nativeEnum(MessageFailedToCreateWorkflow);

/** @internal */
export const ErrorFailedToCreateWorkflow$inboundSchema: z.ZodType<
  ErrorFailedToCreateWorkflow,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageFailedToCreateWorkflow$inboundSchema.optional(),
  details: z.any().optional(),
});

export function errorFailedToCreateWorkflowFromJSON(
  jsonString: string,
): SafeParseResult<ErrorFailedToCreateWorkflow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorFailedToCreateWorkflow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorFailedToCreateWorkflow' from JSON`,
  );
}

/** @internal */
export const MessageProjectNotFound$inboundSchema: z.ZodNativeEnum<
  typeof MessageProjectNotFound
> = z.nativeEnum(MessageProjectNotFound);

/** @internal */
export const ErrorProjectNotFound$inboundSchema: z.ZodType<
  ErrorProjectNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageProjectNotFound$inboundSchema.optional(),
  details: z.any().optional(),
});

export function errorProjectNotFoundFromJSON(
  jsonString: string,
): SafeParseResult<ErrorProjectNotFound, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorProjectNotFound$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorProjectNotFound' from JSON`,
  );
}

/** @internal */
export const PostApiV1CreateBadRequestMessage$inboundSchema: z.ZodNativeEnum<
  typeof PostApiV1CreateBadRequestMessage
> = z.nativeEnum(PostApiV1CreateBadRequestMessage);

/** @internal */
export const PostApiV1CreateBadRequestError$inboundSchema: z.ZodType<
  PostApiV1CreateBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1CreateBadRequestMessage$inboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1CreateBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1CreateBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1CreateBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1CreateBadRequestError' from JSON`,
  );
}

/** @internal */
export const PostApiV1CreateResponse$inboundSchema: z.ZodType<
  PostApiV1CreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflow: z.any().optional(),
  nodes: z.any().optional(),
  edges: z.any().optional(),
});

export function postApiV1CreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1CreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1CreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1CreateResponse' from JSON`,
  );
}
