/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * TODO: grab this from jsdoc and add a default
 */
export type PostApiV1TriggerManualResponse = {
  success?: boolean | undefined;
  /**
   * TODO: This is an unknown type
   */
  executionId?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  triggerExecutionId?: any | null | undefined;
  message?: string | undefined;
};

/** @internal */
export const PostApiV1TriggerManualResponse$inboundSchema: z.ZodType<
  PostApiV1TriggerManualResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  executionId: z.nullable(z.any()).optional(),
  triggerExecutionId: z.nullable(z.any()).optional(),
  message: z.string().optional(),
});

export function postApiV1TriggerManualResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerManualResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1TriggerManualResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerManualResponse' from JSON`,
  );
}
