/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1CreateRequest = {
  xAppId?: string | undefined;
  xAppSecret?: string | undefined;
};

export const MessageFailedToCreateWorkflow = {
  FailedToCreateWorkflow: "Failed to create workflow",
} as const;
export type MessageFailedToCreateWorkflow = ClosedEnum<
  typeof MessageFailedToCreateWorkflow
>;

export type ErrorFailedToCreateWorkflow = {
  message?: MessageFailedToCreateWorkflow | undefined;
  details?: any | undefined;
};

export const MessageProjectNotFound = {
  ProjectNotFound: "Project not found",
} as const;
export type MessageProjectNotFound = ClosedEnum<typeof MessageProjectNotFound>;

export type ErrorProjectNotFound = {
  message?: MessageProjectNotFound | undefined;
  details?: any | undefined;
};

export const PostApiV1CreateBadRequestMessage = {
  MissingRequiredHeaders: "Missing required headers",
  WorkflowMustHaveAtLeastOneNodeAndOneEdge:
    "Workflow must have at least one node and one edge",
} as const;
export type PostApiV1CreateBadRequestMessage = ClosedEnum<
  typeof PostApiV1CreateBadRequestMessage
>;

export type PostApiV1CreateBadRequestError = {
  message?: PostApiV1CreateBadRequestMessage | undefined;
  details?: any | undefined;
};

/**
 * Creates a workflow for a project with the provided nodes and edges.
 */
export type PostApiV1CreateResponse = {
  /**
   * Unknown type
   */
  workflow?: any | undefined;
  /**
   * Unknown type
   */
  nodes?: any | undefined;
  /**
   * Unknown type
   */
  edges?: any | undefined;
};

/** @internal */
export const PostApiV1CreateRequest$inboundSchema: z.ZodType<
  PostApiV1CreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "x-app-id": z.string().optional(),
  "x-app-secret": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "x-app-id": "xAppId",
    "x-app-secret": "xAppSecret",
  });
});
/** @internal */
export type PostApiV1CreateRequest$Outbound = {
  "x-app-id"?: string | undefined;
  "x-app-secret"?: string | undefined;
};

/** @internal */
export const PostApiV1CreateRequest$outboundSchema: z.ZodType<
  PostApiV1CreateRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1CreateRequest
> = z.object({
  xAppId: z.string().optional(),
  xAppSecret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xAppId: "x-app-id",
    xAppSecret: "x-app-secret",
  });
});

export function postApiV1CreateRequestToJSON(
  postApiV1CreateRequest: PostApiV1CreateRequest,
): string {
  return JSON.stringify(
    PostApiV1CreateRequest$outboundSchema.parse(postApiV1CreateRequest),
  );
}
export function postApiV1CreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1CreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1CreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1CreateRequest' from JSON`,
  );
}

/** @internal */
export const MessageFailedToCreateWorkflow$inboundSchema: z.ZodNativeEnum<
  typeof MessageFailedToCreateWorkflow
> = z.nativeEnum(MessageFailedToCreateWorkflow);
/** @internal */
export const MessageFailedToCreateWorkflow$outboundSchema: z.ZodNativeEnum<
  typeof MessageFailedToCreateWorkflow
> = MessageFailedToCreateWorkflow$inboundSchema;

/** @internal */
export const ErrorFailedToCreateWorkflow$inboundSchema: z.ZodType<
  ErrorFailedToCreateWorkflow,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageFailedToCreateWorkflow$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type ErrorFailedToCreateWorkflow$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const ErrorFailedToCreateWorkflow$outboundSchema: z.ZodType<
  ErrorFailedToCreateWorkflow$Outbound,
  z.ZodTypeDef,
  ErrorFailedToCreateWorkflow
> = z.object({
  message: MessageFailedToCreateWorkflow$outboundSchema.optional(),
  details: z.any().optional(),
});

export function errorFailedToCreateWorkflowToJSON(
  errorFailedToCreateWorkflow: ErrorFailedToCreateWorkflow,
): string {
  return JSON.stringify(
    ErrorFailedToCreateWorkflow$outboundSchema.parse(
      errorFailedToCreateWorkflow,
    ),
  );
}
export function errorFailedToCreateWorkflowFromJSON(
  jsonString: string,
): SafeParseResult<ErrorFailedToCreateWorkflow, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorFailedToCreateWorkflow$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorFailedToCreateWorkflow' from JSON`,
  );
}

/** @internal */
export const MessageProjectNotFound$inboundSchema: z.ZodNativeEnum<
  typeof MessageProjectNotFound
> = z.nativeEnum(MessageProjectNotFound);
/** @internal */
export const MessageProjectNotFound$outboundSchema: z.ZodNativeEnum<
  typeof MessageProjectNotFound
> = MessageProjectNotFound$inboundSchema;

/** @internal */
export const ErrorProjectNotFound$inboundSchema: z.ZodType<
  ErrorProjectNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageProjectNotFound$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type ErrorProjectNotFound$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const ErrorProjectNotFound$outboundSchema: z.ZodType<
  ErrorProjectNotFound$Outbound,
  z.ZodTypeDef,
  ErrorProjectNotFound
> = z.object({
  message: MessageProjectNotFound$outboundSchema.optional(),
  details: z.any().optional(),
});

export function errorProjectNotFoundToJSON(
  errorProjectNotFound: ErrorProjectNotFound,
): string {
  return JSON.stringify(
    ErrorProjectNotFound$outboundSchema.parse(errorProjectNotFound),
  );
}
export function errorProjectNotFoundFromJSON(
  jsonString: string,
): SafeParseResult<ErrorProjectNotFound, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorProjectNotFound$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorProjectNotFound' from JSON`,
  );
}

/** @internal */
export const PostApiV1CreateBadRequestMessage$inboundSchema: z.ZodNativeEnum<
  typeof PostApiV1CreateBadRequestMessage
> = z.nativeEnum(PostApiV1CreateBadRequestMessage);
/** @internal */
export const PostApiV1CreateBadRequestMessage$outboundSchema: z.ZodNativeEnum<
  typeof PostApiV1CreateBadRequestMessage
> = PostApiV1CreateBadRequestMessage$inboundSchema;

/** @internal */
export const PostApiV1CreateBadRequestError$inboundSchema: z.ZodType<
  PostApiV1CreateBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1CreateBadRequestMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1CreateBadRequestError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1CreateBadRequestError$outboundSchema: z.ZodType<
  PostApiV1CreateBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1CreateBadRequestError
> = z.object({
  message: PostApiV1CreateBadRequestMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1CreateBadRequestErrorToJSON(
  postApiV1CreateBadRequestError: PostApiV1CreateBadRequestError,
): string {
  return JSON.stringify(
    PostApiV1CreateBadRequestError$outboundSchema.parse(
      postApiV1CreateBadRequestError,
    ),
  );
}
export function postApiV1CreateBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1CreateBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1CreateBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1CreateBadRequestError' from JSON`,
  );
}

/** @internal */
export const PostApiV1CreateResponse$inboundSchema: z.ZodType<
  PostApiV1CreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflow: z.any().optional(),
  nodes: z.any().optional(),
  edges: z.any().optional(),
});
/** @internal */
export type PostApiV1CreateResponse$Outbound = {
  workflow?: any | undefined;
  nodes?: any | undefined;
  edges?: any | undefined;
};

/** @internal */
export const PostApiV1CreateResponse$outboundSchema: z.ZodType<
  PostApiV1CreateResponse$Outbound,
  z.ZodTypeDef,
  PostApiV1CreateResponse
> = z.object({
  workflow: z.any().optional(),
  nodes: z.any().optional(),
  edges: z.any().optional(),
});

export function postApiV1CreateResponseToJSON(
  postApiV1CreateResponse: PostApiV1CreateResponse,
): string {
  return JSON.stringify(
    PostApiV1CreateResponse$outboundSchema.parse(postApiV1CreateResponse),
  );
}
export function postApiV1CreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1CreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1CreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1CreateResponse' from JSON`,
  );
}
