/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1RunsRunIdEventsRequest = {
  runId: string;
};

export const PostApiV1RunsRunIdEventsMessage = {
  InvalidRunEventsPayload: "Invalid run events payload",
  EventRunIdWorkflowIdMismatch: "Event runId/workflowId mismatch",
} as const;
export type PostApiV1RunsRunIdEventsMessage = ClosedEnum<
  typeof PostApiV1RunsRunIdEventsMessage
>;

export type PostApiV1RunsRunIdEventsError = {
  message?: PostApiV1RunsRunIdEventsMessage | undefined;
  details?: any | undefined;
};

/**
 * Appends one or more events to the run event stream for the given run id.
 */
export type PostApiV1RunsRunIdEventsResponse = {
  /**
   * Unknown type
   */
  accepted?: any | undefined;
  /**
   * Unknown type
   */
  events?: any | undefined;
  /**
   * Unknown type
   */
  nextCursor?: any | undefined;
};

/** @internal */
export const PostApiV1RunsRunIdEventsRequest$inboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  runId: z.string(),
});
/** @internal */
export type PostApiV1RunsRunIdEventsRequest$Outbound = {
  runId: string;
};

/** @internal */
export const PostApiV1RunsRunIdEventsRequest$outboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1RunsRunIdEventsRequest
> = z.object({
  runId: z.string(),
});

export function postApiV1RunsRunIdEventsRequestToJSON(
  postApiV1RunsRunIdEventsRequest: PostApiV1RunsRunIdEventsRequest,
): string {
  return JSON.stringify(
    PostApiV1RunsRunIdEventsRequest$outboundSchema.parse(
      postApiV1RunsRunIdEventsRequest,
    ),
  );
}
export function postApiV1RunsRunIdEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RunsRunIdEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RunsRunIdEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RunsRunIdEventsRequest' from JSON`,
  );
}

/** @internal */
export const PostApiV1RunsRunIdEventsMessage$inboundSchema: z.ZodNativeEnum<
  typeof PostApiV1RunsRunIdEventsMessage
> = z.nativeEnum(PostApiV1RunsRunIdEventsMessage);
/** @internal */
export const PostApiV1RunsRunIdEventsMessage$outboundSchema: z.ZodNativeEnum<
  typeof PostApiV1RunsRunIdEventsMessage
> = PostApiV1RunsRunIdEventsMessage$inboundSchema;

/** @internal */
export const PostApiV1RunsRunIdEventsError$inboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1RunsRunIdEventsMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1RunsRunIdEventsError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1RunsRunIdEventsError$outboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsError$Outbound,
  z.ZodTypeDef,
  PostApiV1RunsRunIdEventsError
> = z.object({
  message: PostApiV1RunsRunIdEventsMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1RunsRunIdEventsErrorToJSON(
  postApiV1RunsRunIdEventsError: PostApiV1RunsRunIdEventsError,
): string {
  return JSON.stringify(
    PostApiV1RunsRunIdEventsError$outboundSchema.parse(
      postApiV1RunsRunIdEventsError,
    ),
  );
}
export function postApiV1RunsRunIdEventsErrorFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RunsRunIdEventsError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RunsRunIdEventsError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RunsRunIdEventsError' from JSON`,
  );
}

/** @internal */
export const PostApiV1RunsRunIdEventsResponse$inboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepted: z.any().optional(),
  events: z.any().optional(),
  nextCursor: z.any().optional(),
});
/** @internal */
export type PostApiV1RunsRunIdEventsResponse$Outbound = {
  accepted?: any | undefined;
  events?: any | undefined;
  nextCursor?: any | undefined;
};

/** @internal */
export const PostApiV1RunsRunIdEventsResponse$outboundSchema: z.ZodType<
  PostApiV1RunsRunIdEventsResponse$Outbound,
  z.ZodTypeDef,
  PostApiV1RunsRunIdEventsResponse
> = z.object({
  accepted: z.any().optional(),
  events: z.any().optional(),
  nextCursor: z.any().optional(),
});

export function postApiV1RunsRunIdEventsResponseToJSON(
  postApiV1RunsRunIdEventsResponse: PostApiV1RunsRunIdEventsResponse,
): string {
  return JSON.stringify(
    PostApiV1RunsRunIdEventsResponse$outboundSchema.parse(
      postApiV1RunsRunIdEventsResponse,
    ),
  );
}
export function postApiV1RunsRunIdEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RunsRunIdEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RunsRunIdEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RunsRunIdEventsResponse' from JSON`,
  );
}
