/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1TriggerTriggerIdRequest = {
  triggerId: string;
};

export const PostApiV1TriggerTriggerIdNotFoundMessage = {
  TriggerNotFound: "Trigger not found",
  WorkflowNotFound: "Workflow not found",
} as const;
export type PostApiV1TriggerTriggerIdNotFoundMessage = ClosedEnum<
  typeof PostApiV1TriggerTriggerIdNotFoundMessage
>;

export type PostApiV1TriggerTriggerIdNotFoundError = {
  message?: PostApiV1TriggerTriggerIdNotFoundMessage | undefined;
  details?: any | undefined;
};

export const PostApiV1TriggerTriggerIdForbiddenMessage = {
  TriggerIsDisabled: "Trigger is disabled",
} as const;
export type PostApiV1TriggerTriggerIdForbiddenMessage = ClosedEnum<
  typeof PostApiV1TriggerTriggerIdForbiddenMessage
>;

export type PostApiV1TriggerTriggerIdForbiddenError = {
  message?: PostApiV1TriggerTriggerIdForbiddenMessage | undefined;
  details?: any | undefined;
};

export const PostApiV1TriggerTriggerIdUnauthorizedMessage = {
  Unauthorized: "Unauthorized",
} as const;
export type PostApiV1TriggerTriggerIdUnauthorizedMessage = ClosedEnum<
  typeof PostApiV1TriggerTriggerIdUnauthorizedMessage
>;

export type PostApiV1TriggerTriggerIdUnauthorizedError = {
  message?: PostApiV1TriggerTriggerIdUnauthorizedMessage | undefined;
  details?: any | undefined;
};

export const PostApiV1TriggerTriggerIdBadRequestMessage = {
  TriggerIDIsRequired: "Trigger ID is required",
  InvalidTriggerTypeForThisEndpoint: "Invalid trigger type for this endpoint",
  InvalidJSONPayload: "Invalid JSON payload",
} as const;
export type PostApiV1TriggerTriggerIdBadRequestMessage = ClosedEnum<
  typeof PostApiV1TriggerTriggerIdBadRequestMessage
>;

export type PostApiV1TriggerTriggerIdBadRequestError = {
  message?: PostApiV1TriggerTriggerIdBadRequestMessage | undefined;
  details?: any | undefined;
};

/**
 * Validates the webhook trigger and starts a workflow execution.
 */
export type PostApiV1TriggerTriggerIdResponse = {
  success?: boolean | undefined;
  /**
   * Unknown type
   */
  executionId?: any | undefined;
  /**
   * Unknown type
   */
  triggerExecutionId?: any | undefined;
};

export type PostApiV1TriggerManualRequest = {
  xClientId?: string | undefined;
  xClientSecret?: string | undefined;
};

export const PostApiV1TriggerManualUnauthorizedMessage = {
  ClientCredentialsRequired: "Client credentials required",
  Unauthorized: "Unauthorized",
} as const;
export type PostApiV1TriggerManualUnauthorizedMessage = ClosedEnum<
  typeof PostApiV1TriggerManualUnauthorizedMessage
>;

export type PostApiV1TriggerManualUnauthorizedError = {
  message?: PostApiV1TriggerManualUnauthorizedMessage | undefined;
  details?: any | undefined;
};

export const PostApiV1TriggerManualBadRequestMessage = {
  InvalidJSONBody: "Invalid JSON body",
  TriggerIDIsRequired: "Trigger ID is required",
  ThisEndpointOnlySupportsManualTriggers:
    "This endpoint only supports manual triggers",
} as const;
export type PostApiV1TriggerManualBadRequestMessage = ClosedEnum<
  typeof PostApiV1TriggerManualBadRequestMessage
>;

export type PostApiV1TriggerManualBadRequestError = {
  message?: PostApiV1TriggerManualBadRequestMessage | undefined;
  details?: any | undefined;
};

/**
 * Executes a workflow on-demand using client credentials and an optional payload.
 */
export type PostApiV1TriggerManualResponse = {
  success?: boolean | undefined;
  /**
   * Unknown type
   */
  executionId?: any | undefined;
  /**
   * Unknown type
   */
  triggerExecutionId?: any | undefined;
  message?: string | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdRequest$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  triggerId: z.string(),
});
/** @internal */
export type PostApiV1TriggerTriggerIdRequest$Outbound = {
  triggerId: string;
};

/** @internal */
export const PostApiV1TriggerTriggerIdRequest$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdRequest
> = z.object({
  triggerId: z.string(),
});

export function postApiV1TriggerTriggerIdRequestToJSON(
  postApiV1TriggerTriggerIdRequest: PostApiV1TriggerTriggerIdRequest,
): string {
  return JSON.stringify(
    PostApiV1TriggerTriggerIdRequest$outboundSchema.parse(
      postApiV1TriggerTriggerIdRequest,
    ),
  );
}
export function postApiV1TriggerTriggerIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerTriggerIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1TriggerTriggerIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerTriggerIdRequest' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerTriggerIdNotFoundMessage$inboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdNotFoundMessage> = z
    .nativeEnum(PostApiV1TriggerTriggerIdNotFoundMessage);
/** @internal */
export const PostApiV1TriggerTriggerIdNotFoundMessage$outboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdNotFoundMessage> =
    PostApiV1TriggerTriggerIdNotFoundMessage$inboundSchema;

/** @internal */
export const PostApiV1TriggerTriggerIdNotFoundError$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1TriggerTriggerIdNotFoundMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1TriggerTriggerIdNotFoundError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdNotFoundError$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdNotFoundError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdNotFoundError
> = z.object({
  message: PostApiV1TriggerTriggerIdNotFoundMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1TriggerTriggerIdNotFoundErrorToJSON(
  postApiV1TriggerTriggerIdNotFoundError:
    PostApiV1TriggerTriggerIdNotFoundError,
): string {
  return JSON.stringify(
    PostApiV1TriggerTriggerIdNotFoundError$outboundSchema.parse(
      postApiV1TriggerTriggerIdNotFoundError,
    ),
  );
}
export function postApiV1TriggerTriggerIdNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerTriggerIdNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1TriggerTriggerIdNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerTriggerIdNotFoundError' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerTriggerIdForbiddenMessage$inboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdForbiddenMessage> = z
    .nativeEnum(PostApiV1TriggerTriggerIdForbiddenMessage);
/** @internal */
export const PostApiV1TriggerTriggerIdForbiddenMessage$outboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdForbiddenMessage> =
    PostApiV1TriggerTriggerIdForbiddenMessage$inboundSchema;

/** @internal */
export const PostApiV1TriggerTriggerIdForbiddenError$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1TriggerTriggerIdForbiddenMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1TriggerTriggerIdForbiddenError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdForbiddenError$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdForbiddenError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdForbiddenError
> = z.object({
  message: PostApiV1TriggerTriggerIdForbiddenMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1TriggerTriggerIdForbiddenErrorToJSON(
  postApiV1TriggerTriggerIdForbiddenError:
    PostApiV1TriggerTriggerIdForbiddenError,
): string {
  return JSON.stringify(
    PostApiV1TriggerTriggerIdForbiddenError$outboundSchema.parse(
      postApiV1TriggerTriggerIdForbiddenError,
    ),
  );
}
export function postApiV1TriggerTriggerIdForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiV1TriggerTriggerIdForbiddenError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1TriggerTriggerIdForbiddenError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiV1TriggerTriggerIdForbiddenError' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerTriggerIdUnauthorizedMessage$inboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdUnauthorizedMessage> = z
    .nativeEnum(PostApiV1TriggerTriggerIdUnauthorizedMessage);
/** @internal */
export const PostApiV1TriggerTriggerIdUnauthorizedMessage$outboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdUnauthorizedMessage> =
    PostApiV1TriggerTriggerIdUnauthorizedMessage$inboundSchema;

/** @internal */
export const PostApiV1TriggerTriggerIdUnauthorizedError$inboundSchema:
  z.ZodType<PostApiV1TriggerTriggerIdUnauthorizedError, z.ZodTypeDef, unknown> =
    z.object({
      message: PostApiV1TriggerTriggerIdUnauthorizedMessage$inboundSchema
        .optional(),
      details: z.any().optional(),
    });
/** @internal */
export type PostApiV1TriggerTriggerIdUnauthorizedError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdUnauthorizedError$outboundSchema:
  z.ZodType<
    PostApiV1TriggerTriggerIdUnauthorizedError$Outbound,
    z.ZodTypeDef,
    PostApiV1TriggerTriggerIdUnauthorizedError
  > = z.object({
    message: PostApiV1TriggerTriggerIdUnauthorizedMessage$outboundSchema
      .optional(),
    details: z.any().optional(),
  });

export function postApiV1TriggerTriggerIdUnauthorizedErrorToJSON(
  postApiV1TriggerTriggerIdUnauthorizedError:
    PostApiV1TriggerTriggerIdUnauthorizedError,
): string {
  return JSON.stringify(
    PostApiV1TriggerTriggerIdUnauthorizedError$outboundSchema.parse(
      postApiV1TriggerTriggerIdUnauthorizedError,
    ),
  );
}
export function postApiV1TriggerTriggerIdUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiV1TriggerTriggerIdUnauthorizedError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1TriggerTriggerIdUnauthorizedError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiV1TriggerTriggerIdUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerTriggerIdBadRequestMessage$inboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdBadRequestMessage> = z
    .nativeEnum(PostApiV1TriggerTriggerIdBadRequestMessage);
/** @internal */
export const PostApiV1TriggerTriggerIdBadRequestMessage$outboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerTriggerIdBadRequestMessage> =
    PostApiV1TriggerTriggerIdBadRequestMessage$inboundSchema;

/** @internal */
export const PostApiV1TriggerTriggerIdBadRequestError$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1TriggerTriggerIdBadRequestMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1TriggerTriggerIdBadRequestError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdBadRequestError$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdBadRequestError
> = z.object({
  message: PostApiV1TriggerTriggerIdBadRequestMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1TriggerTriggerIdBadRequestErrorToJSON(
  postApiV1TriggerTriggerIdBadRequestError:
    PostApiV1TriggerTriggerIdBadRequestError,
): string {
  return JSON.stringify(
    PostApiV1TriggerTriggerIdBadRequestError$outboundSchema.parse(
      postApiV1TriggerTriggerIdBadRequestError,
    ),
  );
}
export function postApiV1TriggerTriggerIdBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiV1TriggerTriggerIdBadRequestError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1TriggerTriggerIdBadRequestError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiV1TriggerTriggerIdBadRequestError' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerTriggerIdResponse$inboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  executionId: z.any().optional(),
  triggerExecutionId: z.any().optional(),
});
/** @internal */
export type PostApiV1TriggerTriggerIdResponse$Outbound = {
  success?: boolean | undefined;
  executionId?: any | undefined;
  triggerExecutionId?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerTriggerIdResponse$outboundSchema: z.ZodType<
  PostApiV1TriggerTriggerIdResponse$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerTriggerIdResponse
> = z.object({
  success: z.boolean().optional(),
  executionId: z.any().optional(),
  triggerExecutionId: z.any().optional(),
});

export function postApiV1TriggerTriggerIdResponseToJSON(
  postApiV1TriggerTriggerIdResponse: PostApiV1TriggerTriggerIdResponse,
): string {
  return JSON.stringify(
    PostApiV1TriggerTriggerIdResponse$outboundSchema.parse(
      postApiV1TriggerTriggerIdResponse,
    ),
  );
}
export function postApiV1TriggerTriggerIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerTriggerIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1TriggerTriggerIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerTriggerIdResponse' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerManualRequest$inboundSchema: z.ZodType<
  PostApiV1TriggerManualRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "x-client-id": z.string().optional(),
  "x-client-secret": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "x-client-id": "xClientId",
    "x-client-secret": "xClientSecret",
  });
});
/** @internal */
export type PostApiV1TriggerManualRequest$Outbound = {
  "x-client-id"?: string | undefined;
  "x-client-secret"?: string | undefined;
};

/** @internal */
export const PostApiV1TriggerManualRequest$outboundSchema: z.ZodType<
  PostApiV1TriggerManualRequest$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualRequest
> = z.object({
  xClientId: z.string().optional(),
  xClientSecret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    xClientId: "x-client-id",
    xClientSecret: "x-client-secret",
  });
});

export function postApiV1TriggerManualRequestToJSON(
  postApiV1TriggerManualRequest: PostApiV1TriggerManualRequest,
): string {
  return JSON.stringify(
    PostApiV1TriggerManualRequest$outboundSchema.parse(
      postApiV1TriggerManualRequest,
    ),
  );
}
export function postApiV1TriggerManualRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerManualRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1TriggerManualRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerManualRequest' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerManualUnauthorizedMessage$inboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerManualUnauthorizedMessage> = z
    .nativeEnum(PostApiV1TriggerManualUnauthorizedMessage);
/** @internal */
export const PostApiV1TriggerManualUnauthorizedMessage$outboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerManualUnauthorizedMessage> =
    PostApiV1TriggerManualUnauthorizedMessage$inboundSchema;

/** @internal */
export const PostApiV1TriggerManualUnauthorizedError$inboundSchema: z.ZodType<
  PostApiV1TriggerManualUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1TriggerManualUnauthorizedMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1TriggerManualUnauthorizedError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerManualUnauthorizedError$outboundSchema: z.ZodType<
  PostApiV1TriggerManualUnauthorizedError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualUnauthorizedError
> = z.object({
  message: PostApiV1TriggerManualUnauthorizedMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1TriggerManualUnauthorizedErrorToJSON(
  postApiV1TriggerManualUnauthorizedError:
    PostApiV1TriggerManualUnauthorizedError,
): string {
  return JSON.stringify(
    PostApiV1TriggerManualUnauthorizedError$outboundSchema.parse(
      postApiV1TriggerManualUnauthorizedError,
    ),
  );
}
export function postApiV1TriggerManualUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiV1TriggerManualUnauthorizedError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1TriggerManualUnauthorizedError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiV1TriggerManualUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerManualBadRequestMessage$inboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerManualBadRequestMessage> = z
    .nativeEnum(PostApiV1TriggerManualBadRequestMessage);
/** @internal */
export const PostApiV1TriggerManualBadRequestMessage$outboundSchema:
  z.ZodNativeEnum<typeof PostApiV1TriggerManualBadRequestMessage> =
    PostApiV1TriggerManualBadRequestMessage$inboundSchema;

/** @internal */
export const PostApiV1TriggerManualBadRequestError$inboundSchema: z.ZodType<
  PostApiV1TriggerManualBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: PostApiV1TriggerManualBadRequestMessage$inboundSchema.optional(),
  details: z.any().optional(),
});
/** @internal */
export type PostApiV1TriggerManualBadRequestError$Outbound = {
  message?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const PostApiV1TriggerManualBadRequestError$outboundSchema: z.ZodType<
  PostApiV1TriggerManualBadRequestError$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualBadRequestError
> = z.object({
  message: PostApiV1TriggerManualBadRequestMessage$outboundSchema.optional(),
  details: z.any().optional(),
});

export function postApiV1TriggerManualBadRequestErrorToJSON(
  postApiV1TriggerManualBadRequestError: PostApiV1TriggerManualBadRequestError,
): string {
  return JSON.stringify(
    PostApiV1TriggerManualBadRequestError$outboundSchema.parse(
      postApiV1TriggerManualBadRequestError,
    ),
  );
}
export function postApiV1TriggerManualBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerManualBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1TriggerManualBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerManualBadRequestError' from JSON`,
  );
}

/** @internal */
export const PostApiV1TriggerManualResponse$inboundSchema: z.ZodType<
  PostApiV1TriggerManualResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  executionId: z.any().optional(),
  triggerExecutionId: z.any().optional(),
  message: z.string().optional(),
});
/** @internal */
export type PostApiV1TriggerManualResponse$Outbound = {
  success?: boolean | undefined;
  executionId?: any | undefined;
  triggerExecutionId?: any | undefined;
  message?: string | undefined;
};

/** @internal */
export const PostApiV1TriggerManualResponse$outboundSchema: z.ZodType<
  PostApiV1TriggerManualResponse$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualResponse
> = z.object({
  success: z.boolean().optional(),
  executionId: z.any().optional(),
  triggerExecutionId: z.any().optional(),
  message: z.string().optional(),
});

export function postApiV1TriggerManualResponseToJSON(
  postApiV1TriggerManualResponse: PostApiV1TriggerManualResponse,
): string {
  return JSON.stringify(
    PostApiV1TriggerManualResponse$outboundSchema.parse(
      postApiV1TriggerManualResponse,
    ),
  );
}
export function postApiV1TriggerManualResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerManualResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1TriggerManualResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerManualResponse' from JSON`,
  );
}
