/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MessageFailedToCreateRun = {
  FailedToCreateRun: "Failed to create run",
} as const;
export type MessageFailedToCreateRun = ClosedEnum<
  typeof MessageFailedToCreateRun
>;

export type ErrorFailedToCreateRun = {
  message?: MessageFailedToCreateRun | undefined;
  details?: any | undefined;
};

export const MessageInvalidRunPayload = {
  InvalidRunPayload: "Invalid run payload",
} as const;
export type MessageInvalidRunPayload = ClosedEnum<
  typeof MessageInvalidRunPayload
>;

export type ErrorInvalidRunPayload = {
  message?: MessageInvalidRunPayload | undefined;
  details?: any | undefined;
};

/**
 * Creates a new run for the specified workflow and returns the run metadata.
 */
export type PostApiV1RunsResponse = {
  runId?: any | undefined;
  /**
   * Circular type
   */
  workflowId?: any | undefined;
  /**
   * Circular type
   */
  status?: any | undefined;
  /**
   * Circular type
   */
  nodeStatuses?: any | undefined;
  /**
   * Circular type
   */
  startedAt?: any | undefined;
  /**
   * Circular type
   */
  finishedAt?: any | undefined;
  /**
   * Circular type
   */
  metadata?: any | undefined;
  /**
   * Circular type
   */
  lastEventId?: any | undefined;
};

/** @internal */
export const MessageFailedToCreateRun$inboundSchema: z.ZodNativeEnum<
  typeof MessageFailedToCreateRun
> = z.nativeEnum(MessageFailedToCreateRun);

/** @internal */
export const ErrorFailedToCreateRun$inboundSchema: z.ZodType<
  ErrorFailedToCreateRun,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageFailedToCreateRun$inboundSchema.optional(),
  details: z.any().optional(),
});

export function errorFailedToCreateRunFromJSON(
  jsonString: string,
): SafeParseResult<ErrorFailedToCreateRun, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorFailedToCreateRun$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorFailedToCreateRun' from JSON`,
  );
}

/** @internal */
export const MessageInvalidRunPayload$inboundSchema: z.ZodNativeEnum<
  typeof MessageInvalidRunPayload
> = z.nativeEnum(MessageInvalidRunPayload);

/** @internal */
export const ErrorInvalidRunPayload$inboundSchema: z.ZodType<
  ErrorInvalidRunPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: MessageInvalidRunPayload$inboundSchema.optional(),
  details: z.any().optional(),
});

export function errorInvalidRunPayloadFromJSON(
  jsonString: string,
): SafeParseResult<ErrorInvalidRunPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorInvalidRunPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorInvalidRunPayload' from JSON`,
  );
}

/** @internal */
export const PostApiV1RunsResponse$inboundSchema: z.ZodType<
  PostApiV1RunsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  runId: z.any().optional(),
  workflowId: z.any().optional(),
  status: z.any().optional(),
  nodeStatuses: z.any().optional(),
  startedAt: z.any().optional(),
  finishedAt: z.any().optional(),
  metadata: z.any().optional(),
  lastEventId: z.any().optional(),
});

export function postApiV1RunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RunsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RunsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RunsResponse' from JSON`,
  );
}
