/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * TODO: grab this from jsdoc and add a default
 */
export type PostApiV1TriggerManualResponse = {
  success?: boolean | undefined;
  /**
   * TODO: This is an unknown type
   */
  executionId?: any | null | undefined;
  /**
   * TODO: This is an unknown type
   */
  triggerExecutionId?: any | null | undefined;
  message?: string | undefined;
};

/** @internal */
export const PostApiV1TriggerManualResponse$inboundSchema: z.ZodType<
  PostApiV1TriggerManualResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  executionId: z.nullable(z.any()).optional(),
  triggerExecutionId: z.nullable(z.any()).optional(),
  message: z.string().optional(),
});

/** @internal */
export type PostApiV1TriggerManualResponse$Outbound = {
  success?: boolean | undefined;
  executionId?: any | null | undefined;
  triggerExecutionId?: any | null | undefined;
  message?: string | undefined;
};

/** @internal */
export const PostApiV1TriggerManualResponse$outboundSchema: z.ZodType<
  PostApiV1TriggerManualResponse$Outbound,
  z.ZodTypeDef,
  PostApiV1TriggerManualResponse
> = z.object({
  success: z.boolean().optional(),
  executionId: z.nullable(z.any()).optional(),
  triggerExecutionId: z.nullable(z.any()).optional(),
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1TriggerManualResponse$ {
  /** @deprecated use `PostApiV1TriggerManualResponse$inboundSchema` instead. */
  export const inboundSchema = PostApiV1TriggerManualResponse$inboundSchema;
  /** @deprecated use `PostApiV1TriggerManualResponse$outboundSchema` instead. */
  export const outboundSchema = PostApiV1TriggerManualResponse$outboundSchema;
  /** @deprecated use `PostApiV1TriggerManualResponse$Outbound` instead. */
  export type Outbound = PostApiV1TriggerManualResponse$Outbound;
}

export function postApiV1TriggerManualResponseToJSON(
  postApiV1TriggerManualResponse: PostApiV1TriggerManualResponse,
): string {
  return JSON.stringify(
    PostApiV1TriggerManualResponse$outboundSchema.parse(
      postApiV1TriggerManualResponse,
    ),
  );
}

export function postApiV1TriggerManualResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1TriggerManualResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1TriggerManualResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1TriggerManualResponse' from JSON`,
  );
}
